name = "PolyesterForwardDiff"
uuid = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
authors = ["The Chrises"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
ForwardDiff = "0.10"
Polyester = "0.5, 0.6, 0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
